### ISSUE TITLE
Plugin does not boot with 1.21.1

### ISSUE THREAD

**Issue by Folas1337** [Monoto72/GlobalStats#4]
```
[22:50:20] [Server thread/ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'GlobalStats-2.0.0.jar' in folder 'plugins/.paper-remapped'
org.bukkit.plugin.InvalidPluginException: Unsupported API version 1.21.1
	at org.bukkit.craftbukkit.util.CraftMagicNumbers.checkSupported(CraftMagicNumbers.java:389) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:121) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at io.papermc.paper.plugin.provider.type.spigot.SpigotPluginProvider.createInstance(SpigotPluginProvider.java:35) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:116) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:38) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at io.papermc.paper.plugin.entrypoint.LaunchEntryPointHandler.enter(LaunchEntryPointHandler.java:40) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at org.bukkit.craftbukkit.CraftServer.loadPlugins(CraftServer.java:535) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:290) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1157) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:329) ~[paper-1.21.jar:1.21-1-21c9a7c]
	at java.base/java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by Monoto72** [comment]
Will fix this in the morning. Thank you for reporting this 😃
